### ISSUE TITLE
missing className="task"

### ISSUE THREAD

**Issue by chonghorizons** [meteor/react-tutorial#19]
In Step 5: https://github.com/meteor/react-tutorial/blob/master/tutorial/simple-todos/05-styles.md

The `className="task"` isn't set anywhere.

`className="tasks"` (with an s) is set, but the singular "task" is missing. I will issue a pull request.

**Comment by filipenevola** [comment]
Hi, the problem was in the instruction and not in the code, we don't have "task" className in the code.

It's fixed here.

Thank you for your contribution 😉
