### ISSUE TITLE
Add SSR tutorial

### ISSUE THREAD

**Issue by eugle** [meteor/react-tutorial#24]
The most important issue in React is SSR.
And if one does not learn the SSR in the React , there is no reason to use React.
Especially with Next vs. React.
So practically if we do not learn SSR well in Meteor-React we have no reason to use Meteor-React

[That's an important question. Why close it](https://github.com/meteor/react-tutorial/issues/7)

Because of the SSR problem, a lot of people will switch to NextJS. Although I have now implemented the SSR with the help of the community, there is still the next problem, which is the SSR problem of code splitting. Also using the community package, I feel that Meteor is too small in this area, is Meteor just used for mobile apps, not SEO?

There was also no official solution for splitting the code, the app would be slow and the first screen would be sluggish, which severely affected the use of Meteor and caused more people to switch to NextJS

**Comment by filipenevola** [comment]
Hi, many people use React without SSR.

There are many ways to use any library.

We are discussing about SSR documentation and examples here https://github.com/meteor/meteor-feature-requests/issues/420

SSR is definitely possible with Meteor, we have a core package dedicated only for `server-render` features. 

We are going to discuss details and next steps in the issue linked above.

Here the focus should be the tutorials, we could add a new tutorial covering SSR with Meteor and React. That would be nice.

**Comment by eugle** [comment]
Great, I hope that the tutorial can detail how to use ssr. I saw that the meteor react 2.0 tutorial has been released, but there is no ssr content. I hope that good people can add it. I look forward to it :)
