### ISSUE TITLE
Issues on getting Graphql to work with ToDoApp Tutorial

### ISSUE THREAD

**Issue by davetheus** [meteor/react-tutorial#49]
W20220407-09:55:04.615(-4)? (STDERR) This package has been deprecated and now it only exports makeExecutableSchema.
W20220407-09:55:04.626(-4)? (STDERR) And it will no longer receive updates.
W20220407-09:55:04.626(-4)? (STDERR) We recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.
W20220407-09:55:04.626(-4)? (STDERR) Check out https://www.graphql-tools.com to learn what package you should use instead!
W20220407-09:55:04.723(-4)? (STDERR) /Users/dtheus/.meteor/packages/meteor-tool/.2.7.1.1ebzwnf.mdfl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20220407-09:55:04.724(-4)? (STDERR) 						throw(ex);
W20220407-09:55:04.724(-4)? (STDERR) 						^
W20220407-09:55:04.724(-4)? (STDERR) 
W20220407-09:55:04.724(-4)? (STDERR) TypeError: graphql.getDescription is not a function
W20220407-09:55:04.724(-4)? (STDERR)     at pushComment (/Users/dtheus/Development/crossfiles/node_modules/@graphql-toolkit/schema-merging/index.cjs.js:117:29)
W20220407-09:55:04.724(-4)? (STDERR)     at collectComment (/Users/dtheus/Development/crossfiles/node_modules/@graphql-toolkit/schema-merging/index.cjs.js:93:5)
W20220407-09:55:04.725(-4)? (STDERR)     at /Users/dtheus/Development/crossfiles/node_modules/@graphql-toolkit/schema-merging/index.cjs.js:662:17
W20220407-09:55:04.725(-4)? (STDERR)     at Array.reduce (<anonymous>)
W20220407-09:55:04.725(-4)? (STDERR)     at mergeGraphQLNodes (/Users/dtheus/Development/crossfiles/node_modules/@graphql-toolkit/schema-merging/index.cjs.js:657:18)
W20220407-09:55:04.725(-4)? (STDERR)     at mergeGraphQLTypes (/Users/dtheus/Development/crossfiles/node_modules/@graphql-toolkit/schema-merging/index.cjs.js:754:25)
W20220407-09:55:04.725(-4)? (STDERR)     at Object.mergeTypeDefs (/Users/dtheus/Development/crossfiles/node_modules/@graphql-toolkit/schema-merging/index.cjs.js:709:22)
W20220407-09:55:04.725(-4)? (STDERR)     at Object.mergeTypes (/Users/dtheus/Development/crossfiles/node_modules/merge-graphql-schemas/index.cjs.js:24:26)
W20220407-09:55:04.725(-4)? (STDERR)     at Loader.getSchema (/Users/dtheus/Development/crossfiles/node_modules/graphql-load/dist/index.js:38:47)
W20220407-09:55:04.725(-4)? (STDERR)     at startGraphQLServer (packages/quave:graphql/server.js:14:8)
W20220407-09:55:04.725(-4)? (STDERR)     at module (imports/api/graphql.js:28:1)
W20220407-09:55:04.725(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20220407-09:55:04.726(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20220407-09:55:04.726(-4)? (STDERR)     at Module.moduleLink [as link] (/Users/dtheus/.meteor/packages/modules/.0.18.0.a4zpu9.4einq++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
W20220407-09:55:04.726(-4)? (STDERR)     at module (server/main.js:1:270)
W20220407-09:55:04.726(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)

**Comment by henriquealbert** [comment]
Hi @davetheus, thanks for reporting the issue.
I'm reviewing the react tutorial at the moment and I'll update the GraphQL part asap

**Comment by davetheus** [comment]
Thank you very much... I'll go through it as soon as it's updated.

**Comment by henriquealbert** [comment]
Important note: When installing the graphql and graphql-tools packages, make sure to keep in those versions: `graphql@15.8.0 graphql-tool@7.0.5`. Higher versions are not supported by quave:graphql.

If you use those versions, it should work fine 🙂

**Comment by davetheus** [comment]
Ok, that did it.  Thanks for the help!
